/**
 * emit_screenplay_tables.mjs — write spec/screenplay-tables.json.
 *
 * The screenplay tables are not registry entities, so nothing about
 * them appears in registry.json: not their columns, not the `line_type`
 * vocabulary every one of their rows carries. Spec §1.3 named the two
 * lists they fall into and published the physical DDL, and stopped
 * there.
 *
 * That gap has a cost with a name. A third-party reader building
 * against §1.3 could see that `screenplay_lines.line_type` exists and
 * had nothing to tell it which values are legal, so it guessed
 * `scene_heading` for a scene heading. The real value is `heading`. Its
 * story order came out confidently wrong and NOTHING WAS RAISED —
 * `line_type` is a free TEXT column, so no finding fires on an
 * unrecognised value and no test could have caught it. A silent wrong
 * answer is worse than a refusal, and this file exists to prevent that
 * particular one.
 *
 * WHAT IS DUMPED AND WHAT IS DECLARED.
 *
 * The columns are DUMPED from a freshly initialised database, on
 * emit_schema_sql.mjs's reasoning: a second description of the same
 * tables would be free to drift from `initDatabase` without anything
 * noticing. What is here is what the reference implementation produces.
 *
 * The `line_type` vocabulary is DECLARED, because it cannot be dumped —
 * the column is free TEXT and a database holds whatever was written to
 * it. It is imported from `LineType` in src/fountain/types.ts, the one
 * place the parser, the tokenizer and the FDX importer all agree on, so
 * this file cannot state a vocabulary the implementation does not use.
 * `screenplayTables.test.ts` closes the loop from the other side.
 *
 *   node --experimental-strip-types scripts/emit_screenplay_tables.mjs
 *   node --experimental-strip-types scripts/emit_screenplay_tables.mjs --check
 *
 * `--check` exits non-zero if the checked-in file is stale, for CI.
 */

import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { initDatabase } from "../src/db.ts";
import { loadRegistry } from "../src/registry.ts";
import { LINE_TYPES, LINE_TYPE_NOTES } from "../src/fountain/types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "spec", "screenplay-tables.json");
const REGISTRY = join(HERE, "..", "registry", "registry.json");

const require = createRequire(import.meta.url);
const { DatabaseSync } = require("node:sqlite");

const registry = loadRegistry(JSON.parse(readFileSync(REGISTRY, "utf8")));

const db = new DatabaseSync(":memory:");
const exec = async (sql, params = []) => {
  const stmt = db.prepare(sql);
  return /^\s*(select|pragma)/i.test(sql)
    ? stmt.all(...params) : (stmt.run(...params), []);
};

await initDatabase(exec, registry);

/** What each table is for. Prose, not derivable, so it is stated here. */
const PURPOSE = {
  screenplay_lines:
    "The working screenplay, one row per line. Story order is derived " +
    "from this table (spec §4.1) and never from scene numbers.",
  screenplay_versions:
    "A published snapshot of the screenplay. Metadata only; the lines " +
    "are in screenplay_version_lines.",
  screenplay_version_lines:
    "The lines belonging to one published version. Frozen: a version " +
    "is what the screenplay said, not what it says.",
  screenplay_prop_tags:
    "A span of line text tagged as referring to a prop. Anchored to a " +
    "line by uuid and character offsets, never by row id.",
  screenplay_title_page:
    "Title-page keys and values for the working screenplay. Owned by " +
    "the screenplay rather than a row in its own right, which is why " +
    "it carries no uuid.",
  screenplay_version_title_page:
    "The title page as it stood in one published version.",
};

const uuidExtra = [...registry.uuidExtraTables].sort();
const owned = [...registry.ownedTables].sort();

const tables = {};
for (const name of [...uuidExtra, ...owned]) {
  const info = db.prepare(`PRAGMA table_info(${JSON.stringify(name)})`).all();
  if (info.length === 0) {
    console.error(`[screenplay-tables] table absent: ${name}`);
    process.exit(1);
  }
  tables[name] = {
    identity: uuidExtra.includes(name) ? "uuid" : "owned",
    purpose: PURPOSE[name] ?? "",
    columns: info.map((c) => ({
      name: String(c.name),
      type: String(c.type),
      notNull: c.notnull === 1,
      default: c.dflt_value === null ? null : String(c.dflt_value),
    })),
  };
}

const text = `${JSON.stringify({
  $comment:
    "GENERATED by scf-core/scripts/emit_screenplay_tables.mjs. Do not " +
    "hand-edit. The screenplay infrastructure tables of spec §1.3: " +
    "their columns, dumped from a database created by initDatabase(), " +
    "and the line_type vocabulary, which is a closed set this file " +
    "publishes because the column itself is free TEXT and cannot " +
    "enforce it.",
  schemaVersion: registry.schemaVersion,
  spec: "§1.3",
  identity: {
    uuid:
      "Not registry entities, but they carry uuid row identity on the " +
      "same terms as an entity (spec §6.1).",
    owned:
      "SCF's, and carrying no identity. A title page is a property of " +
      "the screenplay rather than a row in its own right.",
  },
  lineTypeColumn: {
    columns: ["screenplay_lines.line_type",
              "screenplay_version_lines.line_type"],
    closed: true,
    default: "action",
    note:
      "A closed set. The column is declared TEXT and SQLite enforces " +
      "nothing, so a writer CAN store a value outside this set — a " +
      "reader encountering one MUST treat the line as unknown content " +
      "(spec §10.1) and MUST NOT guess a synonym. `scene_heading` is " +
      "not `heading`.",
    values: LINE_TYPES.map((v) => ({
      value: v,
      note: LINE_TYPE_NOTES[v],
    })),
  },
  tables,
}, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing */ }
  if (current !== text) {
    console.error(
      "[screenplay-tables.json] STALE — run: npm run emit-screenplay-tables");
    process.exit(1);
  }
  console.log(
    `[screenplay-tables.json] up to date ` +
    `(${String(Object.keys(tables).length)} tables, ` +
    `${String(LINE_TYPES.length)} line types, ` +
    `schema ${registry.schemaVersion}).`);
} else {
  writeFileSync(OUT, text, "utf8");
  console.log(
    `[screenplay-tables.json] wrote ` +
    `${String(Object.keys(tables).length)} tables, ` +
    `${String(LINE_TYPES.length)} line types, ` +
    `schema ${registry.schemaVersion}.`);
}

db.close();
