// SPDX-License-Identifier: Apache-2.0
/**
 * emit_api_surface.mjs — write spec/api-surface.json.
 *
 * WHAT THIS IS FOR.
 *
 * `src/index.ts` re-exports eighteen modules with `export *`. That is
 * convenient and it means the package has no stated public surface:
 * every helper written for internal use is exported by accident, and
 * nothing distinguishes a name meant for consumers from a name that
 * happens to be reachable.
 *
 * That costs nothing while the package is unpublished. It becomes a
 * compatibility obligation the moment somebody installs it, because a
 * name they can import is a name they will import, and removing it
 * afterwards is a breaking change whether or not it was ever intended
 * as API.
 *
 * WHAT THIS DOES AND DOES NOT DO.
 *
 * This file PINS the surface. It does not DECIDE it. Every exported
 * name is recorded with its kind, so that a name entering or leaving
 * the surface shows up as a diff in review rather than silently, the
 * same guarantee the registry and the finding catalog already have.
 *
 * Deciding which of these are actually API — and cutting the rest to
 * internal — is still owed, and is much cheaper before 1.0 than after.
 * This artifact is the list to do it against.
 *
 * Type-only exports are included. They matter more than value exports
 * to a TypeScript consumer and are invisible at runtime, so a surface
 * derived by importing the module would miss them entirely.
 *
 *   node --experimental-strip-types scripts/emit_api_surface.mjs
 *   node --experimental-strip-types scripts/emit_api_surface.mjs --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, "..");
const OUT = join(PKG, "..", "spec", "api-surface.json");

/** The entry points a consumer can reach, per package.json `exports`. */
const ENTRIES = {
  ".": "src/index.ts",
  "./node": "src/node.ts",
};

const KIND = {
  [ts.SymbolFlags.Function]: "function",
  [ts.SymbolFlags.Class]: "class",
  [ts.SymbolFlags.Interface]: "interface",
  [ts.SymbolFlags.TypeAlias]: "type",
  [ts.SymbolFlags.Enum]: "enum",
  [ts.SymbolFlags.Variable]: "value",
  [ts.SymbolFlags.BlockScopedVariable]: "value",
};

function kindOf(symbol, checker) {
  const resolved = symbol.flags & ts.SymbolFlags.Alias
    ? checker.getAliasedSymbol(symbol)
    : symbol;
  for (const [flag, name] of Object.entries(KIND)) {
    if (resolved.flags & Number(flag)) return name;
  }
  // A const declared with an arrow function reads as a variable; call it
  // what a consumer would call it.
  const decl = resolved.declarations?.[0];
  if (decl && ts.isVariableDeclaration(decl) && decl.initializer
      && (ts.isArrowFunction(decl.initializer)
          || ts.isFunctionExpression(decl.initializer))) {
    return "function";
  }
  return "value";
}

const program = ts.createProgram(
  Object.values(ENTRIES).map((p) => join(PKG, p)),
  {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    allowImportingTsExtensions: true,
    resolveJsonModule: true,
    noEmit: true,
    skipLibCheck: true,
    strict: true,
  },
);
const checker = program.getTypeChecker();

const entries = {};
let total = 0;
for (const [specifier, rel] of Object.entries(ENTRIES)) {
  const source = program.getSourceFile(join(PKG, rel));
  if (!source) {
    console.error(`[api-surface] entry not found: ${rel}`);
    process.exit(1);
  }
  const moduleSymbol = checker.getSymbolAtLocation(source);
  const names = {};
  for (const symbol of checker.getExportsOfModule(moduleSymbol)) {
    names[symbol.getName()] = kindOf(symbol, checker);
  }
  const sorted = Object.keys(names).sort();
  entries[specifier] = {
    module: rel,
    count: sorted.length,
    exports: Object.fromEntries(sorted.map((n) => [n, names[n]])),
  };
  total += sorted.length;
}

const text = `${JSON.stringify({
  $comment:
    "GENERATED by scf-core/scripts/emit_api_surface.mjs. Do not " +
    "hand-edit. Every name a consumer of @minimalhumans/scf-core can " +
    "import, per entry point, with its kind. This PINS the surface so " +
    "a change to it is a visible diff; it does not assert that every " +
    "name here is intended as API. See the file header.",
  package: "@minimalhumans/scf-core",
  stability:
    "The package is unpublished and pre-1.0. Nothing here is stable " +
    "yet, and the set is expected to SHRINK before 1.0 as names " +
    "written for internal use are cut from the entry points.",
  total,
  entries,
}, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing */ }
  if (current !== text) {
    console.error(
      "[api-surface.json] STALE — the public surface changed.\n" +
      "  If that was deliberate, run: npm run emit-api-surface\n" +
      "  If it was not, something internal became importable.");
    process.exit(1);
  }
  console.log(`[api-surface.json] up to date (${String(total)} exports).`);
} else {
  writeFileSync(OUT, text, "utf8");
  console.log(`[api-surface.json] wrote ${String(total)} exports across ` +
              `${String(Object.keys(entries).length)} entry points.`);
}
