// SPDX-License-Identifier: Apache-2.0
/**
 * emit_normative_data.mjs — publish the two remaining normative facts
 * that lived only in TypeScript.
 *
 * The second independent implementation could not comply with two MUSTs
 * for the same reason: the specification cited something that was never
 * published.
 *
 *   §6.3  "The natural key for each of the thirteen link entities is
 *          stated by `junctionKeyFields()`" — a function, not an
 *          artifact. A third party cannot compute a natural key, so it
 *          cannot de-duplicate, merge or validate a junction.
 *
 *   §12.9  Q14 assesses a target query against a rubric. The section
 *          defined the envelope and the severity scale and nothing
 *          about what is assessed, so the reader implemented an
 *          invented rubric and correctly refused to claim anything for
 *          it.
 *
 * Both are DERIVED facts, so both are emitted rather than written: the
 * junction keys from the registry's own reference declarations, the
 * rubrics from `QUERY_PATHS`. This is the third time this move has been
 * needed — after `finding-catalog.json` and `CASES.json` — and it is the
 * same lesson each time. If a MUST cites something, that something has
 * to be a file.
 *
 *   node --experimental-strip-types scripts/emit_normative_data.mjs
 *   node --experimental-strip-types scripts/emit_normative_data.mjs --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadRegistry } from "../src/registry.ts";
import { junctionEntities, junctionKeyFields } from "../src/junctions.ts";
import { QUERY_PATHS } from "../src/queryPaths.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const SPEC = join(HERE, "..", "..", "spec");
const REGISTRY = join(HERE, "..", "registry", "registry.json");

const registry = loadRegistry(JSON.parse(readFileSync(REGISTRY, "utf8")));

// --- junction natural keys, spec §6.3 --------------------------------

const junctions = junctionEntities(registry)
  .map((e) => ({ entity: e.name, keyFields: junctionKeyFields(e) }))
  .sort((a, b) => a.entity.localeCompare(b.entity));

const junctionDoc = {
  $comment:
    "GENERATED by scf-core/scripts/emit_normative_data.mjs. The natural " +
    "key of each link entity, spec/scf-spec.md §6.3. A uuid identifies a " +
    "row within one file; a natural key identifies the same LINK across " +
    "files, and is what merging, de-duplicating and validating stand on.",
  specSection: "§6.3",
  schemaVersion: registry.schemaVersion,
  derivation:
    "Every non-auto-injected reference field the entity declares, then " +
    "entity_type, entity_id and domain where present. Derived from the " +
    "registry; not maintained by hand.",
  entityCount: junctions.length,
  entities: junctions,
};

// --- readiness rubrics, spec §12.9 -----------------------------------

// Every entity a step names must BE an entity. This is the check that
// makes §12.9.1's steps resolvable rather than readable: a typo, a
// renamed entity, or a return to prose fails the build instead of
// shipping a rubric a third party has to interpret.
// loadRegistry() returns entities as a Map keyed by name.
const registryEntities = registry.entities;
const unresolved = [];
for (const [id, path] of Object.entries(QUERY_PATHS)) {
  for (const s of path.steps) {
    for (const name of s.entities) {
      if (!registryEntities.has(name)) unresolved.push(`${id}: ${name}`);
    }
    if (s.filter !== undefined) {
      // The filter column must exist on every entity the step names,
      // or the step describes a subset that cannot be taken.
      for (const name of s.entities) {
        const entity = registryEntities.get(name);
        const has = entity?.fields.some((f) => f.name === s.filter.field);
        if (!has) unresolved.push(`${id}: ${name} has no ${s.filter.field}`);
      }
    }
  }
}
if (unresolved.length > 0) {
  console.error("[normative-data] rubric steps do not resolve against the " +
                "registry:");
  for (const u of unresolved) console.error(`  ${u}`);
  process.exit(1);
}

const rubrics = Object.entries(QUERY_PATHS)
  .map(([id, path]) => ({
    query: id,
    name: path.name,
    params: path.params,
    description: path.description,
    steps: path.steps.map((s) => ({
      // `entities` is the machine-readable part and every name in it is
      // a registry entity, checked above. `label` is derived from it for
      // display and is the only prose here.
      entities: s.entities,
      requirement: s.requirement,
      purpose: s.purpose,
      ...(s.filter === undefined ? {} : { filter: s.filter }),
      ...(s.intent === undefined ? {} : { intent: s.intent }),
      label: s.label,
    })),
  }))
  .sort((a, b) => a.query.localeCompare(b.query));

const rubricDoc = {
  $comment:
    "GENERATED by scf-core/scripts/emit_normative_data.mjs. The rubric " +
    "Q14 assesses a target query against, spec/scf-spec.md §12.9. Each " +
    "step names an entity the target depends on and how much it depends " +
    "on it; a missing `required` step is a blocker, a missing " +
    "`recommended` step a warning, a missing `optional` step a " +
    "suggestion, and a present step an `ok`.",
  specSection: "§12.9",
  schemaVersion: registry.schemaVersion,
  requirementToSeverity: {
    required: "blocker",
    recommended: "warning",
    optional: "suggestion",
    present: "ok",
  },
  $steps:
    "A step's `entities` are REGISTRY ENTITY NAMES, checked against the " +
    "registry at generation time. `filter` narrows the step to a subset " +
    "of those rows and its `values` are a disjunction; `intent` names " +
    "the asset intent whose bundle must resolve. `label` is derived " +
    "from those three for display and is the only prose here — a " +
    "consumer should never parse it.",
  $note:
    "Only queries with a generative or pre-flight consumer have a " +
    "rubric. The analytic queries read whatever exists and have no " +
    "readiness semantics of their own beyond the walkable queries they " +
    "are built from — asking Q14 about one is answered by assessing " +
    "those.",
  queryCount: rubrics.length,
  queries: rubrics,
};

const outputs = [
  ["junction-keys.json", junctionDoc],
  ["readiness-rubrics.json", rubricDoc],
];

const check = process.argv.includes("--check");
let stale = [];

for (const [name, doc] of outputs) {
  const path = join(SPEC, name);
  const text = `${JSON.stringify(doc, null, 2)}\n`;
  if (check) {
    let current = "";
    try { current = readFileSync(path, "utf8"); } catch { /* missing */ }
    if (current !== text) stale.push(name);
  } else {
    writeFileSync(path, text, "utf8");
  }
}

if (check) {
  if (stale.length > 0) {
    console.error(`[normative-data] STALE: ${stale.join(", ")}`);
    console.error("  run: npm run emit-normative-data");
    process.exit(1);
  }
  console.log(
    `[normative-data] up to date (${String(junctions.length)} junctions, ` +
    `${String(rubrics.length)} rubrics).`);
} else {
  console.log(
    `[normative-data] wrote ${String(junctions.length)} junctions, ` +
    `${String(rubrics.length)} rubrics.`);
}
