// SPDX-License-Identifier: Apache-2.0
/**
 * emit_finding_catalog.mjs — write spec/finding-catalog.json.
 *
 * Spec §9.4 makes the catalog normative: every finding MUST carry a code
 * drawn from it and MUST take its severity from it rather than assigning
 * one at the point the finding is raised.
 *
 * It lived only in `findings.ts`, which made that requirement
 * unsatisfiable by anyone else. An independent Python reader invented 21
 * codes of its own and assigned severities locally — the one thing §9.4
 * forbids — and reported its own exit code as "arithmetically 0 and
 * semantically empty", because two implementations agreeing on "clean"
 * while disagreeing about what a finding IS have not agreed on anything.
 *
 * Emitted from the TypeScript rather than maintained beside it, for the
 * same reason `scf-schema.sql` is dumped rather than written: a second
 * copy of a rule is a second rule.
 *
 *   node --experimental-strip-types scripts/emit_finding_catalog.mjs
 *   node --experimental-strip-types scripts/emit_finding_catalog.mjs --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { FINDING_CATALOG, FINDING_SEVERITY_RANK } from "../src/findings.ts";
import { REPORT_FORMAT_VERSION } from "../src/report.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "spec", "finding-catalog.json");
const REGISTRY = join(HERE, "..", "registry", "registry.json");

const schemaVersion = JSON.parse(
  readFileSync(REGISTRY, "utf8")).schemaVersion;

const codes = Object.keys(FINDING_CATALOG).sort();

const doc = {
  $comment:
    "GENERATED by scf-core/scripts/emit_finding_catalog.mjs. The " +
    "normative finding catalog of spec/scf-spec.md §9.4. Every finding " +
    "an implementation reports must carry a code from this file and " +
    "take its severity from here, not from the point the finding is " +
    "raised. Codes are a closed set: adding one is a change to the " +
    "specification.",
  catalogVersion: "1.0",
  specSection: "§9.4",
  schemaVersion,
  reportFormat: REPORT_FORMAT_VERSION,
  severities: Object.entries(FINDING_SEVERITY_RANK)
    .sort((a, b) => a[1] - b[1])
    .map(([name, rank]) => ({
      name,
      rank,
      meaning: {
        error:
          "The data contradicts itself or the specification, and two " +
          "conforming readers would resolve it differently. Not a " +
          "reason to refuse the file (§9.1).",
        warning: "Resolvable, and probably not what the author meant.",
        info: "Worth reporting; nothing is wrong.",
      }[name],
    })),
  ordering: [
    "severity rank ascending",
    "then code, lexicographic",
    "then table, lexicographic",
    "then lowest row id",
  ],
  codeCount: codes.length,
  codes: codes.map((code) => ({
    code,
    severity: FINDING_CATALOG[code].severity,
    title: FINDING_CATALOG[code].title,
    spec: FINDING_CATALOG[code].spec,
  })),
};

const text = `${JSON.stringify(doc, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing */ }
  if (current !== text) {
    console.error(
      "[finding-catalog] STALE — run: npm run emit-finding-catalog");
    process.exit(1);
  }
  console.log(
    `[finding-catalog] up to date (${String(codes.length)} codes).`);
} else {
  writeFileSync(OUT, text, "utf8");
  console.log(
    `[finding-catalog] wrote ${String(codes.length)} codes.`);
}
