/**
 * emit_normative_data.mjs — publish the two remaining normative facts
 * that lived only in TypeScript.
 *
 * The second independent implementation could not comply with two MUSTs
 * for the same reason: the specification cited something that was never
 * published.
 *
 *   §6.3  "The natural key for each of the thirteen link entities is
 *          stated by `junctionKeyFields()`" — a function, not an
 *          artifact. A third party cannot compute a natural key, so it
 *          cannot de-duplicate, merge or validate a junction.
 *
 *   §12.9  Q14 assesses a target query against a rubric. The section
 *          defined the envelope and the severity scale and nothing
 *          about what is assessed, so the reader implemented an
 *          invented rubric and correctly refused to claim anything for
 *          it.
 *
 * Both are DERIVED facts, so both are emitted rather than written: the
 * junction keys from the registry's own reference declarations, the
 * rubrics from `QUERY_PATHS`. This is the third time this move has been
 * needed — after `finding-catalog.json` and `CASES.json` — and it is the
 * same lesson each time. If a MUST cites something, that something has
 * to be a file.
 *
 *   node --experimental-strip-types scripts/emit_normative_data.mjs
 *   node --experimental-strip-types scripts/emit_normative_data.mjs --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadRegistry } from "../src/registry.ts";
import { junctionEntities, junctionKeyFields } from "../src/junctions.ts";
import { QUERY_PATHS } from "../src/queryPaths.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const SPEC = join(HERE, "..", "..", "spec");
const REGISTRY = join(HERE, "..", "registry", "registry.json");

const registry = loadRegistry(JSON.parse(readFileSync(REGISTRY, "utf8")));

// --- junction natural keys, spec §6.3 --------------------------------

const junctions = junctionEntities(registry)
  .map((e) => ({ entity: e.name, keyFields: junctionKeyFields(e) }))
  .sort((a, b) => a.entity.localeCompare(b.entity));

const junctionDoc = {
  $comment:
    "GENERATED by scf-core/scripts/emit_normative_data.mjs. The natural " +
    "key of each link entity, spec/scf-spec.md §6.3. A uuid identifies a " +
    "row within one file; a natural key identifies the same LINK across " +
    "files, and is what merging, de-duplicating and validating stand on.",
  specSection: "§6.3",
  schemaVersion: registry.schemaVersion,
  derivation:
    "Every non-auto-injected reference field the entity declares, then " +
    "entity_type, entity_id and domain where present. Derived from the " +
    "registry; not maintained by hand.",
  entityCount: junctions.length,
  entities: junctions,
};

// --- readiness rubrics, spec §12.9 -----------------------------------

const rubrics = Object.entries(QUERY_PATHS)
  .map(([id, path]) => ({
    query: id,
    name: path.name,
    params: path.params,
    description: path.description,
    steps: path.steps.map((s) => ({
      // `label`, not `entity`. These are written for a person —
      // "performance_state (vocal)", "sound_cue / music_cue",
      // "bundle + *_asset_binding" — and several name two entities, a
      // filtered subset, or a pattern. Publishing them as `entity` would
      // claim they resolve against the registry, and they do not.
      label: s.entity, requirement: s.requirement, purpose: s.purpose,
    })),
  }))
  .sort((a, b) => a.query.localeCompare(b.query));

const rubricDoc = {
  $comment:
    "GENERATED by scf-core/scripts/emit_normative_data.mjs. The rubric " +
    "Q14 assesses a target query against, spec/scf-spec.md §12.9. Each " +
    "step names an entity the target depends on and how much it depends " +
    "on it; a missing `required` step is a blocker, a missing " +
    "`recommended` step a warning, a missing `optional` step a " +
    "suggestion, and a present step an `ok`.",
  specSection: "§12.9",
  schemaVersion: registry.schemaVersion,
  requirementToSeverity: {
    required: "blocker",
    recommended: "warning",
    optional: "suggestion",
    present: "ok",
  },
  $stepLabels:
    "A step's `label` is prose, not a registry entity name: several " +
    "name two entities, a filtered subset, or a pattern. `requirement` " +
    "is the machine-readable part. Making labels resolve against the " +
    "registry is outstanding work — see spec/stability.md.",
  $note:
    "Only queries with a generative or pre-flight consumer have a " +
    "rubric. The analytic queries read whatever exists and have no " +
    "readiness semantics of their own beyond the walkable queries they " +
    "are built from — asking Q14 about one is answered by assessing " +
    "those.",
  queryCount: rubrics.length,
  queries: rubrics,
};

const outputs = [
  ["junction-keys.json", junctionDoc],
  ["readiness-rubrics.json", rubricDoc],
];

const check = process.argv.includes("--check");
let stale = [];

for (const [name, doc] of outputs) {
  const path = join(SPEC, name);
  const text = `${JSON.stringify(doc, null, 2)}\n`;
  if (check) {
    let current = "";
    try { current = readFileSync(path, "utf8"); } catch { /* missing */ }
    if (current !== text) stale.push(name);
  } else {
    writeFileSync(path, text, "utf8");
  }
}

if (check) {
  if (stale.length > 0) {
    console.error(`[normative-data] STALE: ${stale.join(", ")}`);
    console.error("  run: npm run emit-normative-data");
    process.exit(1);
  }
  console.log(
    `[normative-data] up to date (${String(junctions.length)} junctions, ` +
    `${String(rubrics.length)} rubrics).`);
} else {
  console.log(
    `[normative-data] wrote ${String(junctions.length)} junctions, ` +
    `${String(rubrics.length)} rubrics.`);
}
