/**
 * emit_schema_sql.mjs — write spec/scf-schema.sql.
 *
 * The DDL is DUMPED from a freshly initialised database rather than
 * generated from the registry a second time. A second generator would
 * be a second implementation of the same rule, free to drift from
 * `initDatabase` without anything noticing — which is the failure mode
 * the format keeps running into. Dumping means the published DDL is,
 * by construction, the DDL the reference implementation produces.
 *
 *   node --experimental-strip-types scripts/emit_schema_sql.mjs
 *   node --experimental-strip-types scripts/emit_schema_sql.mjs --check
 *
 * `--check` exits non-zero if the checked-in file is stale, for CI.
 */

import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { initDatabase } from "../src/db.ts";
import { loadRegistry } from "../src/registry.ts";
import { SCF_APPLICATION_ID, encodeUserVersion } from "../src/fileIdentity.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "spec", "scf-schema.sql");
const REGISTRY = join(HERE, "..", "registry", "registry.json");

const require = createRequire(import.meta.url);
const { DatabaseSync } = require("node:sqlite");

const registry = loadRegistry(
  JSON.parse(readFileSync(REGISTRY, "utf8")));

const db = new DatabaseSync(":memory:");
const exec = async (sql, params = []) => {
  const stmt = db.prepare(sql);
  return /^\s*(select|pragma)/i.test(sql)
    ? stmt.all(...params) : (stmt.run(...params), []);
};

await initDatabase(exec, registry);

const rows = db.prepare(
  "SELECT type, name, sql FROM sqlite_master " +
  "WHERE sql IS NOT NULL ORDER BY " +
  "CASE type WHEN 'table' THEN 0 ELSE 1 END, name").all();

const header = `-- The SCF physical schema, schema version ${registry.schemaVersion}.
--
-- GENERATED by scf-core/scripts/emit_schema_sql.mjs. Do not hand-edit.
--
-- Dumped from a database created by initDatabase(), so this is the DDL
-- the reference implementation actually produces, not a second
-- description of it.
--
-- This is the physical schema only. It is not the specification: what
-- the tables MEAN is spec/scf-spec.md, and the normative field set is
-- scf-core/registry/registry.json. A database created from this file
-- alone is structurally conforming and semantically empty.
--
-- Header identification (spec §1.2) is not expressible in DDL. Apply it
-- separately:
--
--   PRAGMA application_id = ${String(SCF_APPLICATION_ID)};
--   PRAGMA user_version = ${String(encodeUserVersion(registry.schemaVersion))};
--
-- _scf_meta.schema_version must also be stamped '${registry.schemaVersion}'.

`;

const body = rows
  .map((r) => `${String(r.sql).trim()};`)
  .join("\n\n");

const text = `${header}${body}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing */ }
  if (current !== text) {
    console.error(
      "[scf-schema.sql] STALE — run: npm run emit-schema-sql");
    process.exit(1);
  }
  console.log(
    `[scf-schema.sql] up to date (${String(rows.length)} objects, ` +
    `schema ${registry.schemaVersion}).`);
} else {
  writeFileSync(OUT, text, "utf8");
  console.log(
    `[scf-schema.sql] wrote ${String(rows.length)} objects, ` +
    `schema ${registry.schemaVersion}.`);
}

db.close();
