-- The SCF physical schema, schema version 2.10.
--
-- GENERATED by scf-core/scripts/emit_schema_sql.mjs. Do not hand-edit.
--
-- Dumped from a database created by initDatabase(), so this is the DDL
-- the reference implementation actually produces, not a second
-- description of it.
--
-- This is the physical schema only. It is not the specification: what
-- the tables MEAN is spec/scf-spec.md, and the normative field set is
-- scf-core/registry/registry.json. A database created from this file
-- alone is structurally conforming and semantically empty.
--
-- Header identification (spec §1.2) is not expressible in DDL. Apply it
-- separately:
--
--   PRAGMA application_id = 1396917809;
--   PRAGMA user_version = 2010;
--
-- _scf_meta.schema_version must also be stamped '2.10'.

CREATE TABLE _scf_meta (
    key TEXT PRIMARY KEY,
    value TEXT
  );

CREATE TABLE "act" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "act_number" INTEGER,
  "start_scene_id" INTEGER,
  "function" TEXT,
  "dramatic_question" TEXT,
  "shift" TEXT,
  "summary" TEXT,
  "status" TEXT DEFAULT 'outline',
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "action_sequence" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "sequence_type" TEXT,
  "description" TEXT,
  "style" TEXT,
  "difficulty_level" TEXT,
  "safety_concerns" TEXT,
  "stunt_requirements" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "action_sequence_character" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "action_sequence_id" INTEGER,
  "character_id" INTEGER,
  "role_in_action" TEXT,
  "notes" TEXT
);

CREATE TABLE "actor" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "actor_character_role" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "actor_id" INTEGER,
  "character_id" INTEGER,
  "role_type" TEXT,
  "scope" TEXT DEFAULT 'whole_project',
  "scope_details" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "asset" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "identifier" TEXT,
  "size_bytes" INTEGER,
  "source_mtime" TEXT,
  "content_hash" TEXT,
  "description" TEXT,
  "tags" TEXT,
  "source" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "parent_id" INTEGER,
  "version_label" TEXT,
  "superseded_at" TEXT,
  "superseded_by_id" INTEGER,
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "asset_relationship" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "asset_id" INTEGER,
  "entity_type" TEXT,
  "entity_id" INTEGER,
  "relationship_type" TEXT,
  "notes" TEXT
);

CREATE TABLE "bundle" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "intent" TEXT,
  "description" TEXT,
  "coverage_summary" TEXT,
  "format_hints" TEXT,
  "intended_consumers" TEXT,
  "provenance" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "parent_id" INTEGER,
  "version_label" TEXT,
  "superseded_at" TEXT,
  "superseded_by_id" INTEGER
);

CREATE TABLE "bundle_asset" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "bundle_id" INTEGER,
  "asset_id" INTEGER,
  "role_in_bundle" TEXT,
  "order" INTEGER,
  "notes" TEXT
);

CREATE TABLE "character" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "role" TEXT,
  "archetype" TEXT,
  "age" TEXT,
  "gender" TEXT,
  "pronouns" TEXT,
  "occupation" TEXT,
  "casting_status" TEXT DEFAULT 'tbd',
  "summary" TEXT,
  "backstory" TEXT,
  "motivation" TEXT,
  "flaw" TEXT,
  "arc_description" TEXT,
  "internal_goal" TEXT,
  "external_goal" TEXT,
  "greatest_fear" TEXT,
  "core_belief" TEXT,
  "education_level" TEXT,
  "skills_abilities" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "character_appearance_profile" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "body_type" TEXT,
  "height_proportions" TEXT,
  "age_appearance" TEXT,
  "hair" TEXT,
  "eyes" TEXT,
  "distinguishing_features" TEXT,
  "skin_tone" TEXT,
  "grooming_level" TEXT,
  "visual_distinction" TEXT,
  "silhouette_description" TEXT,
  "visual_shorthand" TEXT,
  "appearance_evolution" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "character_asset_binding" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "bundle_id" INTEGER,
  "is_baseline" INTEGER DEFAULT false,
  "precedence" INTEGER DEFAULT 0,
  "variant_id" INTEGER,
  "physical_state_filter" TEXT,
  "vocal_state_filter" TEXT,
  "scene_range_start_id" INTEGER,
  "scene_range_end_id" INTEGER,
  "act_id" INTEGER,
  "conditions_json" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "character_color_identity" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "primary_color_hex" TEXT,
  "primary_color_name" TEXT,
  "secondary_colors" TEXT,
  "how_manifests" TEXT,
  "why_these_colors" TEXT,
  "consistency_level" TEXT,
  "starting_colors" TEXT,
  "midpoint_shift" TEXT,
  "final_colors" TEXT,
  "color_isolation" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "character_environment_physicality" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "location_id" INTEGER,
  "comfort_level" TEXT,
  "interaction_pattern" TEXT,
  "spatial_use" TEXT,
  "object_interaction" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "character_relationship" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_a_id" INTEGER,
  "character_b_id" INTEGER,
  "relationship_type" TEXT,
  "directionality" TEXT DEFAULT 'mutual',
  "specific_relationship" TEXT,
  "emotional_valence" TEXT,
  "power_dynamic" TEXT,
  "relationship_arc" TEXT,
  "touch_comfort" TEXT,
  "distance_preference" TEXT,
  "eye_contact_pattern" TEXT,
  "body_orientation" TEXT,
  "mirroring_tendencies" TEXT,
  "physical_evolution" TEXT,
  "history" TEXT,
  "current_status" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "character_shot_override" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "shot_id" INTEGER,
  "character_id" INTEGER,
  "override_types" TEXT,
  "bundle_override_id" INTEGER,
  "variant_target_id" INTEGER,
  "visual_delta" TEXT,
  "vocal_delta" TEXT,
  "motion_delta" TEXT,
  "progression_axis" TEXT,
  "progression_value" REAL,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "parent_id" INTEGER,
  "version_label" TEXT,
  "superseded_at" TEXT,
  "superseded_by_id" INTEGER
);

CREATE TABLE "character_variant" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "physical_differences" TEXT,
  "emotional_state" TEXT,
  "context" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "cinematographic_philosophy" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Cinematographic Philosophy',
  "camera_personality" TEXT,
  "movement_philosophy" TEXT,
  "framing_philosophy" TEXT,
  "visual_consistency" TEXT,
  "coverage_style" TEXT,
  "editorial_approach" TEXT,
  "coverage_priorities" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "clip" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "take_id" INTEGER,
  "scene_id" INTEGER,
  "clip_in_timecode" TEXT,
  "clip_out_timecode" TEXT,
  "duration_seconds" INTEGER,
  "clip_type" TEXT,
  "screenplay_line_start_id" INTEGER,
  "screenplay_line_end_id" INTEGER,
  "beat_id" INTEGER,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "clip_character" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "clip_id" INTEGER,
  "character_id" INTEGER,
  "role_in_clip" TEXT DEFAULT 'featured',
  "notes" TEXT
);

CREATE TABLE "clip_prop" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "clip_id" INTEGER,
  "prop_id" INTEGER,
  "role_in_clip" TEXT DEFAULT 'featured',
  "notes" TEXT
);

CREATE TABLE "collaboration_note" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "note_type" TEXT,
  "content" TEXT,
  "priority" TEXT,
  "affected_entities" TEXT,
  "author" TEXT,
  "note_date" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "color_script" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Color Script',
  "format" TEXT,
  "granularity" TEXT,
  "progression_description" TEXT,
  "key_color_moments" TEXT,
  "arc_shape" TEXT,
  "emotional_mapping" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "color_script_entry" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "temperature" TEXT,
  "key_colors" TEXT,
  "palette_shift" TEXT,
  "emotional_intent" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "color_symbolism" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "color_hex" TEXT,
  "primary_symbolism" TEXT,
  "secondary_symbolism" TEXT,
  "emotional_positive" TEXT,
  "emotional_negative" TEXT,
  "evolution_through_story" TEXT,
  "cultural_context" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "costume" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "description" TEXT,
  "silhouette" TEXT,
  "key_garments" TEXT,
  "layers" TEXT,
  "accessories" TEXT,
  "primary_color_hex" TEXT,
  "primary_color_name" TEXT,
  "secondary_colors" TEXT,
  "fabrics" TEXT,
  "texture_qualities" TEXT,
  "condition" TEXT,
  "what_reveals" TEXT,
  "emotional_state_reflected" TEXT,
  "social_signals" TEXT,
  "continuity_notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "costume_design_philosophy" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Costume Design Philosophy',
  "design_approach" TEXT,
  "silhouette_strategy" TEXT,
  "fabric_philosophy" TEXT,
  "formality_spectrum" TEXT,
  "condition_philosophy" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "costume_progression" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "starting_wardrobe" TEXT,
  "starting_meaning" TEXT,
  "progression_stages" TEXT,
  "color_evolution" TEXT,
  "formality_evolution" TEXT,
  "condition_evolution" TEXT,
  "symbolic_meaning" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "costume_scene" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "costume_id" INTEGER,
  "scene_id" INTEGER,
  "condition_in_scene" TEXT,
  "notes" TEXT
);

CREATE TABLE "creative_decision" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "decision_type" TEXT,
  "description" TEXT,
  "rationale" TEXT,
  "alternatives_considered" TEXT,
  "affected_entities" TEXT,
  "decision_date" TEXT,
  "decided_by" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "dialogue_rhythm" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "overall_rhythm" TEXT,
  "pause_pattern" TEXT,
  "overlap_pattern" TEXT,
  "silence_pattern" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "dialogue_sound_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "recording_aesthetic" TEXT,
  "acoustic_environment" TEXT,
  "dialogue_clarity" TEXT,
  "dialogue_layering" TEXT,
  "processing_notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "emotional_arc" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Audience Emotional Arc',
  "opening_emotional_state" TEXT,
  "closing_emotional_state" TEXT,
  "emotional_shape" TEXT,
  "lingering_feelings" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "emotional_beat" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "emotional_arc_id" INTEGER,
  "scene_id" INTEGER,
  "sequence_id" INTEGER,
  "beat_order" INTEGER,
  "target_emotion" TEXT,
  "intensity" INTEGER,
  "beat_trigger" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "entity_anchor" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "subject_type" TEXT,
  "subject_id" INTEGER,
  "subject_variant_id" INTEGER,
  "anchor_type" TEXT,
  "asset_id" INTEGER,
  "frame_number" INTEGER,
  "timecode" TEXT,
  "region_box" TEXT,
  "region_label" TEXT,
  "audio_offset_start_sec" REAL,
  "audio_offset_end_sec" REAL,
  "condition_description" TEXT,
  "physical_state" TEXT,
  "vocal_state" TEXT,
  "environmental_state" TEXT,
  "canonical_status" TEXT DEFAULT 'candidate',
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "identification_strategy" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "primary_character_id" INTEGER,
  "secondary_character_id" INTEGER,
  "audience_position" TEXT,
  "identification_technique" TEXT,
  "emotional_alignment" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "information_strategy" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "knowledge_asymmetry" TEXT,
  "information_withheld" TEXT,
  "reveal_timing" TEXT,
  "audience_position" TEXT,
  "information_layers" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "lighting_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "shot_id" INTEGER,
  "lighting_style" TEXT,
  "contrast_ratio" TEXT,
  "overall_mood" TEXT,
  "light_quality" TEXT,
  "key_source" TEXT,
  "key_direction" TEXT,
  "key_quality" TEXT,
  "key_color_temperature" INTEGER,
  "fill_ratio" TEXT,
  "fill_quality" TEXT,
  "fill_color_temperature" INTEGER,
  "backlight_notes" TEXT,
  "practical_lights" TEXT,
  "ambient_light" TEXT,
  "lighting_evolution" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "location" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_type" TEXT,
  "setting" TEXT,
  "time_period" TEXT,
  "geography" TEXT,
  "realization_status" TEXT DEFAULT 'tbd',
  "key_features" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "location_asset_binding" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_id" INTEGER,
  "bundle_id" INTEGER,
  "is_baseline" INTEGER DEFAULT false,
  "precedence" INTEGER DEFAULT 0,
  "variant_id" INTEGER,
  "scene_range_start_id" INTEGER,
  "scene_range_end_id" INTEGER,
  "act_id" INTEGER,
  "time_of_day_filter" TEXT,
  "conditions_json" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "location_color_scheme" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_id" INTEGER,
  "dominant_colors" TEXT,
  "color_motivation" TEXT,
  "color_atmosphere" TEXT,
  "color_intensity" TEXT,
  "character_location_interaction" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "location_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_id" INTEGER,
  "design_concept" TEXT,
  "visual_metaphor" TEXT,
  "emotional_target" TEXT,
  "period_style" TEXT,
  "condition" TEXT,
  "scale" TEXT,
  "geometry" TEXT,
  "dominant_materials" TEXT,
  "secondary_materials" TEXT,
  "texture_quality" TEXT,
  "surface_finish" TEXT,
  "spatial_description" TEXT,
  "sight_lines" TEXT,
  "key_focal_points" TEXT,
  "natural_light_sources" TEXT,
  "practical_light_sources" TEXT,
  "light_quality" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "location_shot_override" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "shot_id" INTEGER,
  "location_id" INTEGER,
  "override_types" TEXT,
  "bundle_override_id" INTEGER,
  "variant_target_id" INTEGER,
  "visual_delta" TEXT,
  "acoustic_delta" TEXT,
  "lighting_delta" TEXT,
  "progression_axis" TEXT,
  "progression_value" REAL,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "parent_id" INTEGER,
  "version_label" TEXT,
  "superseded_at" TEXT,
  "superseded_by_id" INTEGER
);

CREATE TABLE "location_sound_profile" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_id" INTEGER,
  "room_tone" TEXT,
  "reverb_quality" TEXT,
  "resonance" TEXT,
  "constant_sounds" TEXT,
  "variable_sounds" TEXT,
  "characteristic_sounds" TEXT,
  "sonic_perspective" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "location_variant" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "location_id" INTEGER,
  "is_baseline" INTEGER DEFAULT false,
  "time_of_day" TEXT,
  "weather" TEXT,
  "season" TEXT,
  "post_event_state" TEXT,
  "physical_differences" TEXT,
  "lighting_differences" TEXT,
  "emotional_shift" TEXT,
  "time_context" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "look_development" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Look Development',
  "contrast" TEXT,
  "saturation" TEXT,
  "color_bias" TEXT,
  "highlight_handling" TEXT,
  "shadow_handling" TEXT,
  "grain_texture" TEXT,
  "on_set_lut" TEXT,
  "editorial_lut" TEXT,
  "final_grade_foundation" TEXT,
  "reference_images" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "makeup_hair_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "scene_id" INTEGER,
  "makeup_approach" TEXT,
  "makeup_details" TEXT,
  "hair_style" TEXT,
  "hair_condition" TEXT,
  "hair_notes" TEXT,
  "prosthetics" TEXT,
  "aging_effects" TEXT,
  "injury_effects" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "motif" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "modality" TEXT,
  "recurrence" TEXT,
  "description" TEXT,
  "literal_function" TEXT,
  "symbolic_meaning" TEXT,
  "secondary_meaning" TEXT,
  "emotional_associations" TEXT,
  "first_appearance_scene_id" INTEGER,
  "recurrence_pattern" TEXT,
  "placement_strategy" TEXT,
  "subtlety_level" TEXT,
  "evolution_description" TEXT,
  "related_motif_id" INTEGER,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "motif_appearance" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "motif_id" INTEGER,
  "scene_id" INTEGER,
  "entity_type" TEXT,
  "entity_id" INTEGER,
  "domain" TEXT,
  "manifestation_notes" TEXT
);

CREATE TABLE "motif_state" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "motif_id" INTEGER,
  "scene_id" INTEGER,
  "stage_description" TEXT,
  "subtlety_level" TEXT,
  "meaning_shift" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "movement_choreography" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "movement_concept" TEXT,
  "rhythm_pattern" TEXT,
  "spatial_pattern" TEXT,
  "ensemble_coordination" TEXT,
  "style_reference" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "music_cue" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "cue_type" TEXT,
  "entry_timing" TEXT,
  "exit_timing" TEXT,
  "duration_seconds" INTEGER,
  "musical_theme_id" INTEGER,
  "emotional_function" TEXT,
  "dynamics" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "music_sound_relationship" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "relationship_type" TEXT,
  "integration_approach" TEXT,
  "dynamic_balance" TEXT,
  "frequency_separation" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "musical_theme" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "theme_type" TEXT,
  "associated_entity" TEXT,
  "description" TEXT,
  "instrumentation" TEXT,
  "variations" TEXT,
  "evolution_description" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "performance_beat" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "character_id" INTEGER,
  "beat_order" INTEGER,
  "modality" TEXT,
  "description" TEXT,
  "trigger" TEXT,
  "emotional_subtext" TEXT,
  "line_text" TEXT,
  "line_ref" TEXT,
  "emphasis_words" TEXT,
  "pace" TEXT,
  "volume" TEXT,
  "delivery_notes" TEXT,
  "physical_action" TEXT,
  "body_part_focus" TEXT,
  "visibility" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "performance_corpus" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Performance Corpus',
  "shoot_dates_start" TEXT,
  "shoot_dates_end" TEXT,
  "shoot_locations" TEXT,
  "coverage_completeness" TEXT DEFAULT 'planned',
  "camera_metadata" TEXT,
  "audio_metadata" TEXT,
  "corpus_notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "performance_state" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "scene_id" INTEGER,
  "shot_id" INTEGER,
  "modality" TEXT,
  "persistence" TEXT,
  "resolved_at_scene_id" INTEGER,
  "state_description" TEXT,
  "modulations" TEXT,
  "emotional_coloring" TEXT,
  "trigger" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "physical_character_profile" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "posture" TEXT,
  "center_of_gravity" TEXT,
  "tension_level" TEXT,
  "energy_quality" TEXT,
  "movement_style" TEXT,
  "movement_speed" TEXT,
  "movement_fluidity" TEXT,
  "movement_economy" TEXT,
  "movement_weight" TEXT,
  "resting_face" TEXT,
  "expressiveness_level" TEXT,
  "facial_asymmetries" TEXT,
  "eye_contact_patterns" TEXT,
  "gaze_direction_tendencies" TEXT,
  "mouth_tension_patterns" TEXT,
  "smile_authenticity" TEXT,
  "spatial_presence" TEXT,
  "physical_comfort" TEXT,
  "coordination_level" TEXT,
  "emotional_manifestations" TEXT,
  "physical_training_visible" TEXT,
  "physical_neglect_visible" TEXT,
  "injuries_visible_in_movement" TEXT,
  "physical_notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "physical_habit" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "description" TEXT,
  "body_parts_involved" TEXT,
  "habit_trigger" TEXT,
  "frequency" TEXT,
  "meaning" TEXT,
  "character_awareness" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "project" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "logline" TEXT,
  "genre" TEXT,
  "tone" TEXT,
  "setting_period" TEXT,
  "target_runtime" INTEGER,
  "project_format" TEXT,
  "production_status" TEXT DEFAULT 'development',
  "workflow_mode" TEXT DEFAULT 'generation_first',
  "scene_numbering" TEXT DEFAULT 'derived',
  "notes" TEXT,
  "vision_statement" TEXT,
  "creative_philosophy" TEXT,
  "themes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "project_color_palette" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Project Color Palette',
  "primary_colors" TEXT,
  "secondary_colors" TEXT,
  "accent_colors" TEXT,
  "restricted_colors" TEXT,
  "saturation_philosophy" TEXT,
  "value_structure" TEXT,
  "temperature_approach" TEXT,
  "temperature_associations" TEXT,
  "temperature_contrast_points" TEXT,
  "day_scene_temperature" TEXT,
  "night_scene_temperature" TEXT,
  "color_evolution" TEXT,
  "color_relationships" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "project_tone" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Project Tone',
  "primary_tone" TEXT,
  "tone_blend" TEXT,
  "lightest_moment" TEXT,
  "darkest_moment" TEXT,
  "tonal_consistency" TEXT,
  "reference_touchstones" TEXT,
  "overall_pacing" TEXT,
  "pacing_philosophy" TEXT,
  "breathing_room_strategy" TEXT,
  "pacing_inflection_points" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "project_vision" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Project Vision',
  "vision_statement" TEXT,
  "core_question" TEXT,
  "intended_audience_impact" TEXT,
  "unique_perspective" TEXT,
  "why_tell_this_story" TEXT,
  "what_makes_different" TEXT,
  "success_criteria" TEXT,
  "filmmaking_philosophy" TEXT,
  "technical_approach" TEXT,
  "aesthetic_priorities" TEXT,
  "risk_tolerance" TEXT,
  "audience_relationship" TEXT,
  "personal_resonance" TEXT,
  "emotional_stakes" TEXT,
  "artistic_growth_goals" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "prop" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "prop_type" TEXT,
  "description" TEXT,
  "realization_status" TEXT DEFAULT 'tbd',
  "narrative_significance" TEXT,
  "story_function" TEXT,
  "associated_character_id" INTEGER,
  "first_appearance" TEXT,
  "key_moments" TEXT,
  "symbolism" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "prop_asset_binding" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "prop_id" INTEGER,
  "bundle_id" INTEGER,
  "is_baseline" INTEGER DEFAULT false,
  "precedence" INTEGER DEFAULT 0,
  "variant_id" INTEGER,
  "scene_range_start_id" INTEGER,
  "scene_range_end_id" INTEGER,
  "act_id" INTEGER,
  "conditions_json" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "prop_shot_override" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "shot_id" INTEGER,
  "prop_id" INTEGER,
  "override_types" TEXT,
  "bundle_override_id" INTEGER,
  "variant_target_id" INTEGER,
  "visual_delta" TEXT,
  "surface_delta" TEXT,
  "motion_delta" TEXT,
  "progression_axis" TEXT,
  "progression_value" REAL,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "parent_id" INTEGER,
  "version_label" TEXT,
  "superseded_at" TEXT,
  "superseded_by_id" INTEGER
);

CREATE TABLE "prop_state" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "prop_id" INTEGER,
  "scene_id" INTEGER,
  "custody_character_id" INTEGER,
  "condition" TEXT,
  "whereabouts" TEXT,
  "significance_note" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "prop_surface_profile" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "prop_id" INTEGER,
  "material" TEXT,
  "secondary_materials" TEXT,
  "size" TEXT,
  "weight_impression" TEXT,
  "primary_color_hex" TEXT,
  "primary_color_name" TEXT,
  "secondary_colors" TEXT,
  "surface_finish" TEXT,
  "texture_quality" TEXT,
  "baseline_condition" TEXT,
  "wear_pattern" TEXT,
  "aging_notes" TEXT,
  "visual_distinction" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "prop_variant" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "prop_id" INTEGER,
  "physical_differences" TEXT,
  "state_trigger" TEXT,
  "context" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "relationship_state" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_relationship_id" INTEGER,
  "scene_id" INTEGER,
  "stage_label" TEXT,
  "description" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "scene" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_number" TEXT,
  "int_ext" TEXT,
  "location_id" INTEGER,
  "time_of_day" TEXT,
  "weather_conditions" TEXT,
  "season" TEXT,
  "summary" TEXT,
  "purpose" TEXT,
  "status" TEXT DEFAULT 'outline',
  "characters_present" TEXT,
  "character_dynamics" TEXT,
  "emotional_beat" TEXT,
  "tone" TEXT,
  "tension_level" INTEGER,
  "thematic_connection" TEXT,
  "visual_style" TEXT,
  "sound_design" TEXT,
  "music_notes" TEXT,
  "estimated_duration" INTEGER,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "scene_blocking" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "staging_concept" TEXT,
  "character_geography" TEXT,
  "blocking_evolution" TEXT,
  "proxemics" TEXT,
  "camera_relationship" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "scene_character" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "character_id" INTEGER,
  "role_in_scene" TEXT,
  "notes" TEXT
);

CREATE TABLE "scene_color_palette" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "dominant_colors" TEXT,
  "color_harmony_type" TEXT,
  "color_source_distribution" TEXT,
  "color_contrast_level" TEXT,
  "focal_color" TEXT,
  "grading_notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "scene_emotional_target" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "primary_emotion" TEXT,
  "primary_intensity" INTEGER,
  "secondary_emotions" TEXT,
  "emotional_function" TEXT,
  "audience_character_relationship" TEXT,
  "contrast_with_previous" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "scene_music_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "music_presence" TEXT,
  "emotional_function" TEXT,
  "entry_point" TEXT,
  "build_evolution" TEXT,
  "peak" TEXT,
  "exit_point" TEXT,
  "themes_used" TEXT,
  "source_music_description" TEXT,
  "lyrics_relevance" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "scene_prop" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "prop_id" INTEGER,
  "usage_note" TEXT,
  "significance" TEXT
);

CREATE TABLE "scene_sequence" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "sequence_id" INTEGER,
  "order_in_sequence" INTEGER
);

CREATE TABLE screenplay_lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scene_id INTEGER REFERENCES scene(id) ON DELETE SET NULL,
    line_order INTEGER NOT NULL,
    line_type TEXT NOT NULL DEFAULT 'action',
    content TEXT NOT NULL DEFAULT '',
    character_id INTEGER REFERENCES character(id) ON DELETE SET NULL,
    location_id INTEGER REFERENCES location(id) ON DELETE SET NULL,
    metadata JSON,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  , uuid TEXT);

CREATE TABLE screenplay_prop_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tagged_text TEXT NOT NULL,
    prop_id INTEGER NOT NULL REFERENCES prop(id) ON DELETE CASCADE,
    created_at TEXT DEFAULT (datetime('now'))
  , line_uuid TEXT, start_offset INTEGER, end_offset INTEGER, uuid TEXT);

CREATE TABLE screenplay_title_page (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT '',
    sort_order INTEGER DEFAULT 0
  );

CREATE TABLE screenplay_version_lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_id INTEGER NOT NULL
      REFERENCES screenplay_versions(id) ON DELETE CASCADE,
    line_order INTEGER NOT NULL,
    line_type TEXT NOT NULL DEFAULT 'action',
    content TEXT NOT NULL DEFAULT '',
    scene_id INTEGER,
    character_id INTEGER,
    location_id INTEGER,
    metadata JSON,
    source_uuid TEXT
  , uuid TEXT);

CREATE TABLE screenplay_version_title_page (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_id INTEGER NOT NULL
      REFERENCES screenplay_versions(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT '',
    sort_order INTEGER DEFAULT 0
  );

CREATE TABLE screenplay_versions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_number INTEGER NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    published_at TEXT DEFAULT (datetime('now')),
    line_count INTEGER DEFAULT 0,
    scene_count INTEGER DEFAULT 0,
    character_count INTEGER DEFAULT 0,
    location_count INTEGER DEFAULT 0,
    word_count INTEGER DEFAULT 0
  , uuid TEXT);

CREATE TABLE "sequence" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "sequence_number" INTEGER,
  "act_id" INTEGER,
  "start_scene_id" INTEGER,
  "summary" TEXT,
  "goal" TEXT,
  "conflict" TEXT,
  "outcome" TEXT,
  "purpose" TEXT,
  "turning_point" TEXT,
  "status" TEXT DEFAULT 'outline',
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "set_dressing" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "location_id" INTEGER,
  "hero_objects" TEXT,
  "atmospheric_objects" TEXT,
  "practical_objects" TEXT,
  "background_fill" TEXT,
  "sightline_management" TEXT,
  "continuity_requirements" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "shot" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "shot_number" TEXT,
  "shot_order" INTEGER,
  "story_beat_id" INTEGER,
  "shot_size" TEXT,
  "camera_angle" TEXT,
  "camera_movement" TEXT,
  "lens_choice" TEXT,
  "duration_seconds" REAL,
  "description" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "shot_coverage" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "shot_id" INTEGER,
  "coverage_state" TEXT,
  "source_take_id" INTEGER,
  "source_clip_id" INTEGER,
  "generation_required" TEXT,
  "override_summary" TEXT,
  "status_date" TEXT,
  "decided_by" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "shot_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "shot_id" INTEGER,
  "composition_type" TEXT,
  "frame_division" TEXT,
  "subject_placement" TEXT,
  "negative_space" TEXT,
  "depth_of_field" TEXT,
  "focus_strategy" TEXT,
  "color_emphasis" TEXT,
  "textural_emphasis" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "shot_language" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "visual_strategy" TEXT,
  "shot_relationships" TEXT,
  "cutting_pattern" TEXT,
  "rhythm" TEXT,
  "transitions" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "sonic_identity" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Sonic Identity',
  "sound_aesthetic" TEXT,
  "sonic_density" TEXT,
  "silence_philosophy" TEXT,
  "subjective_sound_approach" TEXT,
  "sound_evolution" TEXT,
  "score_approach" TEXT,
  "musical_tone" TEXT,
  "instrumentation_palette" TEXT,
  "score_density" TEXT,
  "source_music_approach" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "sound_cue" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "shot_id" INTEGER,
  "sound_type" TEXT,
  "description" TEXT,
  "timing" TEXT,
  "duration" TEXT,
  "emotional_function" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "sound_perspective" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "perspective_type" TEXT,
  "pov_character_id" INTEGER,
  "spatial_logic" TEXT,
  "psychological_logic" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE "staging_beat" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_blocking_id" INTEGER,
  "action_sequence_id" INTEGER,
  "beat_order" INTEGER,
  "description" TEXT,
  "characters_involved" TEXT,
  "character_positions" TEXT,
  "movement_description" TEXT,
  "camera_note" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "story_beat" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "beat_order" INTEGER,
  "beat_type" TEXT,
  "description" TEXT,
  "purpose" TEXT,
  "value_shift" TEXT,
  "pov_character_id" INTEGER,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "subtext" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "surface_level" TEXT,
  "subtext_level" TEXT,
  "gap_size" TEXT,
  "character_awareness" TEXT,
  "audience_access" TEXT,
  "purpose" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "take" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "corpus_id" INTEGER,
  "shot_id" INTEGER,
  "take_number" INTEGER,
  "date_recorded" TEXT,
  "duration_seconds" INTEGER,
  "timecode_start" TEXT,
  "timecode_end" TEXT,
  "preferred" INTEGER DEFAULT false,
  "camera_designation" TEXT,
  "lens_info" TEXT,
  "recording_format" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active',
  "external_id" TEXT,
  "external_id_namespace" TEXT
);

CREATE TABLE "take_scene" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "take_id" INTEGER,
  "scene_id" INTEGER,
  "order_in_take" INTEGER,
  "coverage_completeness" TEXT DEFAULT 'complete',
  "notes" TEXT
);

CREATE TABLE "technical_specs" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Technical Specs',
  "aspect_ratio" TEXT,
  "resolution" TEXT,
  "frame_rate" TEXT,
  "color_space" TEXT,
  "recording_codec" TEXT,
  "delivery_format" TEXT,
  "audio_format" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "thematic_connection" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "theme_id" INTEGER,
  "entity_type" TEXT,
  "entity_id" INTEGER,
  "nature_of_connection" TEXT,
  "subtlety_level" TEXT,
  "intended_perception" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "theme" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "description" TEXT,
  "motifs" TEXT,
  "character_connections" TEXT,
  "scene_connections" TEXT,
  "evolution" TEXT,
  "notes" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "tone_marker" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "sequence_id" INTEGER,
  "tone_descriptor" TEXT,
  "intensity" TEXT,
  "genre_elements" TEXT,
  "mood_atmosphere" TEXT,
  "pacing_expectation" TEXT,
  "tonal_shift" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "visual_identity" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT DEFAULT 'Visual Identity',
  "visual_statement" TEXT,
  "aesthetic_genre" TEXT,
  "design_era" TEXT,
  "visual_density" TEXT,
  "primary_materials" TEXT,
  "secondary_materials" TEXT,
  "accent_materials" TEXT,
  "forbidden_materials" TEXT,
  "material_storytelling" TEXT,
  "textural_philosophy" TEXT,
  "texture_contrast_strategy" TEXT,
  "surface_finish_preference" TEXT,
  "patina_aging_approach" TEXT,
  "technology_level" TEXT,
  "technology_aesthetic" TEXT,
  "architectural_styles" TEXT,
  "scale_rules" TEXT,
  "geometric_language" TEXT,
  "lighting_constraints" TEXT,
  "visual_influences" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "vocal_profile" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "character_id" INTEGER,
  "voice_quality" TEXT,
  "pitch_range" TEXT,
  "timbre" TEXT,
  "volume_tendency" TEXT,
  "breathiness_level" TEXT,
  "speech_pattern" TEXT,
  "pace" TEXT,
  "rhythm" TEXT,
  "articulation" TEXT,
  "fluency" TEXT,
  "accent" TEXT,
  "regional_markers" TEXT,
  "class_markers" TEXT,
  "educational_markers" TEXT,
  "accent_authenticity" TEXT,
  "delivery_style" TEXT,
  "emotional_access" TEXT,
  "subtext_playing" TEXT,
  "listening_behavior" TEXT,
  "interruption_tendencies" TEXT,
  "vocal_habits" TEXT,
  "filler_words" TEXT,
  "catch_phrases" TEXT,
  "verbal_tics" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE TABLE "voiceover_design" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  "name" TEXT,
  "scene_id" INTEGER,
  "character_id" INTEGER,
  "voiceover_type" TEXT,
  "voiceover_function" TEXT,
  "temporal_position" TEXT,
  "knowledge_position" TEXT,
  "relationship_to_image" TEXT,
  "lifecycle_status" TEXT DEFAULT 'active'
);

CREATE UNIQUE INDEX "idx_act_uuid" ON "act"(uuid);

CREATE UNIQUE INDEX "idx_action_sequence_character_uuid" ON "action_sequence_character"(uuid);

CREATE UNIQUE INDEX "idx_action_sequence_uuid" ON "action_sequence"(uuid);

CREATE UNIQUE INDEX "idx_actor_character_role_uuid" ON "actor_character_role"(uuid);

CREATE UNIQUE INDEX "idx_actor_uuid" ON "actor"(uuid);

CREATE UNIQUE INDEX "idx_asset_relationship_uuid" ON "asset_relationship"(uuid);

CREATE UNIQUE INDEX "idx_asset_uuid" ON "asset"(uuid);

CREATE UNIQUE INDEX "idx_bundle_asset_uuid" ON "bundle_asset"(uuid);

CREATE UNIQUE INDEX "idx_bundle_uuid" ON "bundle"(uuid);

CREATE UNIQUE INDEX "idx_character_appearance_profile_uuid" ON "character_appearance_profile"(uuid);

CREATE UNIQUE INDEX "idx_character_asset_binding_uuid" ON "character_asset_binding"(uuid);

CREATE UNIQUE INDEX "idx_character_color_identity_uuid" ON "character_color_identity"(uuid);

CREATE UNIQUE INDEX "idx_character_environment_physicality_uuid" ON "character_environment_physicality"(uuid);

CREATE UNIQUE INDEX "idx_character_relationship_uuid" ON "character_relationship"(uuid);

CREATE UNIQUE INDEX "idx_character_shot_override_uuid" ON "character_shot_override"(uuid);

CREATE UNIQUE INDEX "idx_character_uuid" ON "character"(uuid);

CREATE UNIQUE INDEX "idx_character_variant_uuid" ON "character_variant"(uuid);

CREATE UNIQUE INDEX "idx_cinematographic_philosophy_uuid" ON "cinematographic_philosophy"(uuid);

CREATE UNIQUE INDEX "idx_clip_character_uuid" ON "clip_character"(uuid);

CREATE UNIQUE INDEX "idx_clip_prop_uuid" ON "clip_prop"(uuid);

CREATE UNIQUE INDEX "idx_clip_uuid" ON "clip"(uuid);

CREATE UNIQUE INDEX "idx_collaboration_note_uuid" ON "collaboration_note"(uuid);

CREATE UNIQUE INDEX "idx_color_script_entry_uuid" ON "color_script_entry"(uuid);

CREATE UNIQUE INDEX "idx_color_script_uuid" ON "color_script"(uuid);

CREATE UNIQUE INDEX "idx_color_symbolism_uuid" ON "color_symbolism"(uuid);

CREATE UNIQUE INDEX "idx_costume_design_philosophy_uuid" ON "costume_design_philosophy"(uuid);

CREATE UNIQUE INDEX "idx_costume_progression_uuid" ON "costume_progression"(uuid);

CREATE UNIQUE INDEX "idx_costume_scene_uuid" ON "costume_scene"(uuid);

CREATE UNIQUE INDEX "idx_costume_uuid" ON "costume"(uuid);

CREATE UNIQUE INDEX "idx_creative_decision_uuid" ON "creative_decision"(uuid);

CREATE UNIQUE INDEX "idx_dialogue_rhythm_uuid" ON "dialogue_rhythm"(uuid);

CREATE UNIQUE INDEX "idx_dialogue_sound_design_uuid" ON "dialogue_sound_design"(uuid);

CREATE UNIQUE INDEX "idx_emotional_arc_uuid" ON "emotional_arc"(uuid);

CREATE UNIQUE INDEX "idx_emotional_beat_uuid" ON "emotional_beat"(uuid);

CREATE UNIQUE INDEX "idx_entity_anchor_uuid" ON "entity_anchor"(uuid);

CREATE UNIQUE INDEX "idx_identification_strategy_uuid" ON "identification_strategy"(uuid);

CREATE UNIQUE INDEX "idx_information_strategy_uuid" ON "information_strategy"(uuid);

CREATE UNIQUE INDEX "idx_lighting_design_uuid" ON "lighting_design"(uuid);

CREATE UNIQUE INDEX "idx_location_asset_binding_uuid" ON "location_asset_binding"(uuid);

CREATE UNIQUE INDEX "idx_location_color_scheme_uuid" ON "location_color_scheme"(uuid);

CREATE UNIQUE INDEX "idx_location_design_uuid" ON "location_design"(uuid);

CREATE UNIQUE INDEX "idx_location_shot_override_uuid" ON "location_shot_override"(uuid);

CREATE UNIQUE INDEX "idx_location_sound_profile_uuid" ON "location_sound_profile"(uuid);

CREATE UNIQUE INDEX "idx_location_uuid" ON "location"(uuid);

CREATE UNIQUE INDEX "idx_location_variant_uuid" ON "location_variant"(uuid);

CREATE UNIQUE INDEX "idx_look_development_uuid" ON "look_development"(uuid);

CREATE UNIQUE INDEX "idx_makeup_hair_design_uuid" ON "makeup_hair_design"(uuid);

CREATE UNIQUE INDEX "idx_motif_appearance_uuid" ON "motif_appearance"(uuid);

CREATE UNIQUE INDEX "idx_motif_state_uuid" ON "motif_state"(uuid);

CREATE UNIQUE INDEX "idx_motif_uuid" ON "motif"(uuid);

CREATE UNIQUE INDEX "idx_movement_choreography_uuid" ON "movement_choreography"(uuid);

CREATE UNIQUE INDEX "idx_music_cue_uuid" ON "music_cue"(uuid);

CREATE UNIQUE INDEX "idx_music_sound_relationship_uuid" ON "music_sound_relationship"(uuid);

CREATE UNIQUE INDEX "idx_musical_theme_uuid" ON "musical_theme"(uuid);

CREATE UNIQUE INDEX "idx_performance_beat_uuid" ON "performance_beat"(uuid);

CREATE UNIQUE INDEX "idx_performance_corpus_uuid" ON "performance_corpus"(uuid);

CREATE UNIQUE INDEX "idx_performance_state_uuid" ON "performance_state"(uuid);

CREATE UNIQUE INDEX "idx_physical_character_profile_uuid" ON "physical_character_profile"(uuid);

CREATE UNIQUE INDEX "idx_physical_habit_uuid" ON "physical_habit"(uuid);

CREATE UNIQUE INDEX "idx_project_color_palette_uuid" ON "project_color_palette"(uuid);

CREATE UNIQUE INDEX "idx_project_tone_uuid" ON "project_tone"(uuid);

CREATE UNIQUE INDEX "idx_project_uuid" ON "project"(uuid);

CREATE UNIQUE INDEX "idx_project_vision_uuid" ON "project_vision"(uuid);

CREATE UNIQUE INDEX "idx_prop_asset_binding_uuid" ON "prop_asset_binding"(uuid);

CREATE UNIQUE INDEX "idx_prop_shot_override_uuid" ON "prop_shot_override"(uuid);

CREATE UNIQUE INDEX "idx_prop_state_uuid" ON "prop_state"(uuid);

CREATE UNIQUE INDEX "idx_prop_surface_profile_uuid" ON "prop_surface_profile"(uuid);

CREATE INDEX idx_prop_tags_prop
    ON screenplay_prop_tags(prop_id);

CREATE UNIQUE INDEX "idx_prop_uuid" ON "prop"(uuid);

CREATE UNIQUE INDEX "idx_prop_variant_uuid" ON "prop_variant"(uuid);

CREATE UNIQUE INDEX "idx_relationship_state_uuid" ON "relationship_state"(uuid);

CREATE UNIQUE INDEX "idx_scene_blocking_uuid" ON "scene_blocking"(uuid);

CREATE UNIQUE INDEX "idx_scene_character_uuid" ON "scene_character"(uuid);

CREATE UNIQUE INDEX "idx_scene_color_palette_uuid" ON "scene_color_palette"(uuid);

CREATE UNIQUE INDEX "idx_scene_emotional_target_uuid" ON "scene_emotional_target"(uuid);

CREATE UNIQUE INDEX "idx_scene_music_design_uuid" ON "scene_music_design"(uuid);

CREATE UNIQUE INDEX "idx_scene_prop_uuid" ON "scene_prop"(uuid);

CREATE UNIQUE INDEX "idx_scene_sequence_uuid" ON "scene_sequence"(uuid);

CREATE UNIQUE INDEX "idx_scene_uuid" ON "scene"(uuid);

CREATE INDEX idx_screenplay_lines_order
    ON screenplay_lines(line_order);

CREATE INDEX idx_screenplay_lines_scene
    ON screenplay_lines(scene_id);

CREATE UNIQUE INDEX "idx_screenplay_lines_uuid" ON "screenplay_lines"(uuid);

CREATE UNIQUE INDEX "idx_screenplay_prop_tags_uuid" ON "screenplay_prop_tags"(uuid);

CREATE UNIQUE INDEX "idx_screenplay_version_lines_uuid" ON "screenplay_version_lines"(uuid);

CREATE UNIQUE INDEX "idx_screenplay_versions_uuid" ON "screenplay_versions"(uuid);

CREATE UNIQUE INDEX "idx_sequence_uuid" ON "sequence"(uuid);

CREATE UNIQUE INDEX "idx_set_dressing_uuid" ON "set_dressing"(uuid);

CREATE UNIQUE INDEX "idx_shot_coverage_uuid" ON "shot_coverage"(uuid);

CREATE UNIQUE INDEX "idx_shot_design_uuid" ON "shot_design"(uuid);

CREATE UNIQUE INDEX "idx_shot_language_uuid" ON "shot_language"(uuid);

CREATE UNIQUE INDEX "idx_shot_uuid" ON "shot"(uuid);

CREATE UNIQUE INDEX "idx_sonic_identity_uuid" ON "sonic_identity"(uuid);

CREATE UNIQUE INDEX "idx_sound_cue_uuid" ON "sound_cue"(uuid);

CREATE UNIQUE INDEX "idx_sound_perspective_uuid" ON "sound_perspective"(uuid);

CREATE UNIQUE INDEX "idx_staging_beat_uuid" ON "staging_beat"(uuid);

CREATE UNIQUE INDEX "idx_story_beat_uuid" ON "story_beat"(uuid);

CREATE UNIQUE INDEX "idx_subtext_uuid" ON "subtext"(uuid);

CREATE UNIQUE INDEX "idx_take_scene_uuid" ON "take_scene"(uuid);

CREATE UNIQUE INDEX "idx_take_uuid" ON "take"(uuid);

CREATE UNIQUE INDEX "idx_technical_specs_uuid" ON "technical_specs"(uuid);

CREATE UNIQUE INDEX "idx_thematic_connection_uuid" ON "thematic_connection"(uuid);

CREATE UNIQUE INDEX "idx_theme_uuid" ON "theme"(uuid);

CREATE UNIQUE INDEX "idx_tone_marker_uuid" ON "tone_marker"(uuid);

CREATE INDEX idx_version_lines_version
    ON screenplay_version_lines(version_id);

CREATE UNIQUE INDEX "idx_visual_identity_uuid" ON "visual_identity"(uuid);

CREATE UNIQUE INDEX "idx_vocal_profile_uuid" ON "vocal_profile"(uuid);

CREATE UNIQUE INDEX "idx_voiceover_design_uuid" ON "voiceover_design"(uuid);
