#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
artifact_manifest.py — record the published artifacts for a schema
version, with checksums.

The registry, the physical DDL and the fixture need to be fetchable BY
VERSION and verifiable once fetched. The obvious way to do that is to
commit a copy per version, and that is the wrong way: registry.json is
400KB and would be duplicated on every bump, immediately raising the
question of which copy is real.

Git already versions files. What was missing is an addressing scheme and
a way to check that what you downloaded is what was published. So:

  - a `schema-X.Y` tag pins the tree,
  - the raw URL at that tag is the artifact's address,
  - this manifest carries the SHA-256 so a consumer can verify it.

    python3 schema/artifact_manifest.py            # write
    python3 schema/artifact_manifest.py --check    # verify, for CI

--check fails if any artifact's hash has moved without the manifest
being regenerated, which is the same guarantee the registry generator
gives, applied to publication rather than generation.
"""
import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from schema_meta import SCHEMA_VERSION  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "spec" / "ARTIFACTS.md"
REPO = "https://raw.githubusercontent.com/MinimalHumans/SCF_studio"

ARTIFACTS = [
    ("scf-core/registry/registry.json",
     "The normative field set. Spec §2.1."),
    ("spec/scf-schema.sql",
     "The physical DDL, dumped from initDatabase(). Spec §1.3."),
    ("spec/screenplay-tables.json",
     "The screenplay infrastructure tables and the `line_type` "
     "vocabulary. Spec §1.3."),
    ("spec/registry.schema.json",
     "JSON Schema for registry.json, so it can be consumed without "
     "running the reference implementation."),
    ("spec/junction-keys.json",
     "Natural keys for every link entity. Spec §6.3."),
    ("spec/readiness-rubrics.json",
     "What Q14 assesses, per target query. Spec §12.9.1."),
    ("spec/finding-catalog.json",
     "The normative finding catalog. Spec §9.4 requires every code and "
     "severity to come from here."),
    ("fixtures/expectations/Q00.result.json",
     "Q00's normative result. Spec §12.12."),
    ("fixtures/expectations/Q03.result.json",
     "Q03's normative result. Spec §12.4."),
    ("fixtures/expectations/Q01.result.json",
     "Q01's normative result. Spec §12.15."),
    ("fixtures/expectations/Q02.result.json",
     "Q02's normative result. Spec §12.16."),
    ("fixtures/expectations/Q04.result.json",
     "Q04's normative result. Spec §12.17."),
    ("fixtures/expectations/Q05.result.json",
     "Q05's normative result. Spec §12.2."),
    ("fixtures/expectations/Q07.result.json",
     "Q07's normative result. Spec §12.3."),
    ("fixtures/expectations/Q06.result.json",
     "Q06's normative result. Spec §12.6."),
    ("fixtures/expectations/Q08.result.json",
     "Q08's normative result. Spec §12.7."),
    ("fixtures/expectations/Q09.result.json",
     "Q09's normative result. Spec §12.10."),
    ("fixtures/expectations/Q10.result.json",
     "Q10's normative result. Spec §12.11."),
    ("fixtures/expectations/Q11.result.json",
     "Q11's normative result. Spec §12.13."),
    ("fixtures/expectations/Q12.result.json",
     "Q12's normative result. Spec §12.5."),
    ("fixtures/expectations/Q13.result.json",
     "Q13's normative result. Spec §12.8."),
    ("fixtures/expectations/Q14.result.json",
     "Q14's normative result. Spec §12.9."),
    ("fixtures/expectations/Q15.result.json",
     "Q15's normative result. Spec §12.14."),
    ("fixtures/negative/CASES.json",
     "The eleven negative fixtures as reproducible recipes. Spec "
     "conformance.md §5.3."),
    ("spec/scf.magic",
     "magic(5) stanza for file(1). Spec §1.2."),
    ("fixtures/hollow_creek.scf",
     "The conformance fixture. Its load-bearing properties are "
     "enumerated in spec/conformance.md §5.1."),
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def render() -> str:
    tag = f"schema-{SCHEMA_VERSION}"
    lines = [
        "# Published artifacts",
        "",
        "GENERATED by `schema/artifact_manifest.py`. Do not hand-edit.",
        "",
        f"Schema version **{SCHEMA_VERSION}**, tag `{tag}`.",
        "",
        "## Addressing",
        "",
        "A tag pins the tree; the raw URL at that tag is the artifact's",
        "address. Nothing is duplicated per version — git already stores",
        "the history, and a second copy in the working tree would only",
        "raise the question of which one is real.",
        "",
        "```",
        f"{REPO}/{tag}/<path>",
        "```",
        "",
        "So the registry for this version is:",
        "",
        "```",
        f"{REPO}/{tag}/scf-core/registry/registry.json",
        "```",
        "",
        "`main` is a moving target and MUST NOT be used to pin a version.",
        "",
        "## Verification",
        "",
        "```sh",
        "sha256sum -c spec/SHA256SUMS",
        "```",
        "",
        "## Artifacts",
        "",
        "| Artifact | SHA-256 | What it is |",
        "|---|---|---|",
    ]
    sums = []
    for rel, desc in ARTIFACTS:
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"missing artifact: {rel}")
        digest = sha256(path)
        sums.append(f"{digest}  {rel}")
        lines.append(f"| `{rel}` | `{digest[:16]}…` | {desc} |")
    lines += [
        "",
        "Full digests are in [`SHA256SUMS`](SHA256SUMS).",
        "",
        "## Releasing a schema version",
        "",
        "Step 6 of the change procedure in `docs/conventions.md` §8:",
        "",
        "```sh",
        "python3 schema/artifact_manifest.py",
        f"git tag -s {tag} -m 'schema {SCHEMA_VERSION}'",
        f"git push origin {tag}",
        "```",
        "",
        "The tag is what makes the URLs above resolve. Until it exists,",
        "this manifest describes an address that 404s.",
        "",
    ]
    return "\n".join(lines), "\n".join(sums) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify without writing; non-zero if stale")
    args = ap.parse_args()

    manifest, sums = render()
    sums_path = ROOT / "spec" / "SHA256SUMS"

    if args.check:
        stale = []
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != manifest:
            stale.append(str(OUT.relative_to(ROOT)))
        if (not sums_path.exists()
                or sums_path.read_text(encoding="utf-8") != sums):
            stale.append(str(sums_path.relative_to(ROOT)))
        if stale:
            print("[artifacts] STALE: " + ", ".join(stale))
            print("  run: python3 schema/artifact_manifest.py")
            return 1
        print(f"[artifacts] up to date ({len(ARTIFACTS)} artifacts, "
              f"schema {SCHEMA_VERSION}).")
        return 0

    OUT.write_text(manifest, encoding="utf-8")
    sums_path.write_text(sums, encoding="utf-8")
    print(f"[artifacts] wrote {len(ARTIFACTS)} artifacts, "
          f"schema {SCHEMA_VERSION}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
